/** Shared primitive aliases used across every entity. */

/** Calendar date with no time component, `YYYY-MM-DD`. */
export type DateString = string;

/** Full timestamp in ISO 8601 / UTC, e.g. `2026-09-01T10:15:00.000Z`. */
export type TimestampString = string;

/**
 * Month partition key, `YYYY-MM`.
 *
 * Collections carry one in a real column; follow-ups derive theirs from
 * `followUpDate`. It is what makes historical months immutable: a new month
 * simply starts writing rows with a new key, and nothing earlier is touched.
 */
export type MonthKey = string;

/** Monetary amount in rupees. Stored as a plain number, never a formatted string. */
export type Amount = number;

/** Row identifier generated by the backend (never the sheet row index). */
export type EntityId = string;

/** The `createdAt` / `updatedAt` pair present on most sheets. */
export interface AuditFields {
  readonly createdAt: TimestampString | null;
  readonly updatedAt: TimestampString | null;
}
